# Generated by Django 4.2.30 on 2026-05-01 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '__first__'),
        ('buildings', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_rate', models.DecimalField(decimal_places=2, default=8.0, max_digits=10)),
                ('gas_charge', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('gas_distribution', models.CharField(choices=[('equal', 'Equal'), ('floor', 'Floor-based'), ('manual', 'Manual')], default='equal', max_length=20)),
                ('water_charge', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('water_distribution', models.CharField(choices=[('equal', 'Equal'), ('floor', 'Floor-based'), ('manual', 'Manual')], default='equal', max_length=20)),
                ('service_charge', models.DecimalField(decimal_places=2, default=1500, max_digits=10)),
                ('service_distribution', models.CharField(choices=[('equal', 'Equal'), ('floor', 'Floor-based'), ('manual', 'Manual')], default='equal', max_length=20)),
                ('generator_charge', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('generator_distribution', models.CharField(choices=[('equal', 'Equal'), ('floor', 'Floor-based'), ('manual', 'Manual')], default='equal', max_length=20)),
                ('guard_charge', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('guard_distribution', models.CharField(choices=[('equal', 'Equal'), ('floor', 'Floor-based'), ('manual', 'Manual')], default='equal', max_length=20)),
                ('cleaner_charge', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('cleaner_distribution', models.CharField(choices=[('equal', 'Equal'), ('floor', 'Floor-based'), ('manual', 'Manual')], default='equal', max_length=20)),
                ('due_day', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Billing Settings',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prev_electricity_reading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('curr_electricity_reading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('electricity_units', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('electricity_rate', models.DecimalField(decimal_places=2, default=8.0, max_digits=10)),
                ('electricity_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('water', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generator', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('guard', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cleaner', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bkash', 'bKash')], max_length=20, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='tenants.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='buildings.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', 'unit'],
                'unique_together': {('unit', 'month')},
            },
        ),
    ]
